### ISSUE TITLE
Out of memory exception when handling dart message in Android

### ISSUE THREAD

**Issue by JordyLangen** [braze-inc/braze-flutter-sdk#11]
We noticed the following crash in crashlytics:

```
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 16 byte allocation with 82152 free bytes and 80KB until OOM, target footprint 201326592, growth limit 201326592; failed due to fragmentation (largest possible contiguous allocation 163315712 bytes)

com.braze.brazeplugin.BrazePlugin.convertToAppboyProperties (BrazePlugin.java)
com.braze.brazeplugin.BrazePlugin.onMethodCall (BrazePlugin.java:1697)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage (MethodChannel.java:17)
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart (DartMessenger.java:49)
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:4)
```

```
flutter_error_exception
TimeoutException after 0:00:10.000000: Future not completed
```

Specifications:

**Device**
Brand:samsung
Model:Galaxy Tab S6 Lite
Orientation: Portrait
RAM free: 1.2 GB
Disk free: 39.32 GB

**Operating System**
Version:Android 11
Orientation: Portrait
Rooted:No

**Comment by Bucimis** [comment]
@JordyLangen was this a one-off or are you seeing lots of errors like this? Most likely, something else in the application or the device was taking up a bunch of memory and the work in `convertToAppboyProperties` was the final allocation that put the device over the top into an OOM state (kind of like the straw that broke the camel's back). The fact that the Braze SDK happened to be doing work at the time the device ran out of memory doesn't necessarily mean it was the cause, unless you are seeing this pattern repeatedly

**Comment by JordyLangen** [comment]
@Bucimis I had the same thought initially, as only one user was affected since today. But this was the only out of memory error we could find so far, so I thought it was be worth mentioning it here.

**Comment by JordyLangen** [comment]
Also the fact that we had a timeout on the flutter side had me thinking this may be a specific issue, instead of a "random" OOM error.

**Comment by Bucimis** [comment]
@JordyLangen Thanks for the context. Do you log any excessively large or nested properties objects, or very large string fields?

The implementation for `convertToAppboyProperties` (currently called `convertToBrazeProperties`) is here: https://github.com/braze-inc/braze-flutter-sdk/blob/3aaee8c4cf8cb083b394a31f832c8a2d83f17fc5/android/src/main/kotlin/com/braze/brazeplugin/BrazePlugin.kt#L447

It initializes a `BrazeProperties` object (which is just a wrapper around an initially empty) `JSONObject` and adds objects from the supplied properties map to it. The only object of arbitrary size is String.

**Comment by JordyLangen** [comment]
@Bucimis thanks for the insights, we'll have a look on our side

**Comment by hokstuff** [comment]
Hi @JordyLangen,

Just checking, are you still experiencing this issue?

Thanks!
