### ISSUE TITLE
Add minimum OS version for Android  & iOS in flutter documentation

### ISSUE THREAD

**Issue by brizaldi** [braze-inc/braze-flutter-sdk#13]
Hi, after exploring this plugin for awhile, it seems the documentation for flutter doesn't explain the minimum OS version to use this plugin. I think it's nice to include this in the documentation.

**Comment by radixdev** [comment]
[Android supports API 16+](https://github.com/Appboy/appboy-android-sdk#version-information)
[iOS supports 9.0+
](https://github.com/Appboy/appboy-ios-sdk#version-support)
We will be looking into making this clearer in the plugin itself, thanks for filing!

**Comment by brizaldi** [comment]
Alright thank you, that's good to hear
