### ISSUE TITLE
Onclick android push notification, app is crashing

### ISSUE THREAD

**Issue by santhosh-mobile-engineer** [braze-inc/braze-flutter-sdk#16]
We are using braze sdk with our flutter app . In iOS side things are working fine . But when it comes to android, on click of push notification app is crashing (when app is in background). 

Do you guys have any sample to illustrate working and handling of android push notifications? 

We didn't get any exception  in the logs . The logs we got when push notifications is as follows:

BMP:BackgroundEventManager(1
6492): Activity paused:
com.braze.push.NotificationTram
polineActivity
I/BMP:LifecycleCallbacks(16492):
Activity Paused:
com.braze.push.NotificationTram
polineActivity
[/BMP:LifecycleCallbacks(16492):
Activity Destroyed:
com.maersk.trackandtrace.maers
kshipment_trackandtrace.MainAc
tivity
I/BMP:LifecycleCallbacks(16492):
Activity
Stopped:com.braze.push.Notifica
tionTrampolineActivity
I/BMP:LifecycleCallbacks(16492):
Activity Destroyed:
com.braze.push.NotificationTram
polineActivity

**Comment by Bucimis** [comment]
@santhosh-mobile-engineer if you remove all filters from Logcat, do you see anything? I'd be surprised if Android is crashing without saying anything at all

**Comment by santhosh-mobile-engineer** [comment]
As my target is android 12 , app can't start activities by from services or broadcast receivers that are used as notification trampolines. 

https://developer.android.com/about/versions/12/behavior-changes-12

I think this is causing problem as SDK might need to get an update to support these android 12 changes (if it's already updated , please let me know ) . 

When it comes to integration, We have done all the android setups, as mentioned in docs . But on-click of notifications terminate lifecycle method is called. 

BMP:BackgroundEventManager(1
8411): Activity paused:
com.braze.push.NotificationTram
polineActivity
I/BMP:LifecycleCallbacks(18411)
Activity Paused:
com.braze.push.NotificationTram
polineActivity
I/BMP:LifecycleCallbacks(18411)
Activity Destroyed:
com.maersk.trackandtrace.maers
kshipment_trackandtrace.MainAc
tivitv
I/BMP:LifecycleCallbacks(18411):
Activity
Stopped:com.braze.push.Notifica
tionTrampolineActivity
I/BMP:LifecycleCallbacks(18411):
Activity Destroyed:
com.braze.push.NotificationTram
polineActivity

This is the log we get when app is terminated ..

**Comment by radixdev** [comment]
Hi @santhosh-mobile-engineer ,

The core Braze Android SDK added bespoke support for Android 12 in versions [13.1.0 to 13.1.2](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#1310). 

Additionally, it looks like this issue is currently being routed through support since we need more sensitive files (like your APK, verbose logs, and concrete steps to reproduce on our end) than is appropriate for a public issue like this.

**Comment by santhosh-mobile-engineer** [comment]
I hope this part of log might help to understand issue : 

D/Braze
v17.0.0 .bo.app.z5(11736): New
incoming <push_click>,
Searching for matching triggers.
D/Braze
v17.0.0 .bo.app.z5(11736): Failed
to match triggered action for
incoming <push_click>.

**Comment by radixdev** [comment]
Hi @santhosh-mobile-engineer ,

Unfortunately that's not enough information to fix the issue. Usually with the APK file in hand we can address the issue incredibly quickly.

**Comment by santhosh-mobile-engineer** [comment]
Thanks for you replies . We found the problem . It was with the uri format . We were sending string instead of url . So that's causing the issue . I will close this issue .
