### ISSUE TITLE
Handling push notifications on-click navigation in flutter app

### ISSUE THREAD

**Issue by santhosh-mobile-engineer** [braze-inc/braze-flutter-sdk#17]
Is there any methods available to handle routing in flutter app when user click on push notification? 

Currently on-click push notification it's just opening app and there's no control in flutter side to handle routing .

**Comment by followthemoney1** [comment]
we were using `uni_links` to do this, I'm not sure that Braze worked in correct way

**Comment by spaluchiewicz** [comment]
@santhosh-mobile-engineer I think you should take a look into **Deep Linking**:
- https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/advanced_use_cases/linking/#ats-requirements
- https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking/#android-deep-linking

This task is app dependent and it's hard to provide common solution (I think that's reason it's not provided).

Based on the native tutorial you will have to provide additional implementation into the **braze-flutter-sdk** to be able to bridge data between native and Flutter.

There is also option to use custom payload in push notification (**KEY VALUE PAIRS**) for this purpose.

**Comment by hokstuff** [comment]
Hi all,

Sorry about the delay here and thanks for your input @spaluchiewicz!

Currently, we don't support push notification delegate methods in the Dart layer, and you will need to [follow steps to add them into the native layer](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/push_notifications/). For implementing deep links, you can follow the post above for specific steps and different options. We are exploring different ways to simplify how we interface with push notifications directly in the Dart layer.

Thanks!

**Comment by hokstuff** [comment]
Hi all,

I'm closing out this issue since the original post has the current recommended approach explained in the comments above. If you run into further issues, feel free to open a new issue or email support@braze.com.

Thanks!
