### ISSUE TITLE
SDK authentication support in Flutter

### ISSUE THREAD

**Issue by crystalztl** [braze-inc/braze-flutter-sdk#19]
Refer to: https://www.braze.com/docs/developer_guide/platform_wide/sdk_authentication/#create-jwt 
The sdkAuthSignature  parameter is not found in flutter SDK changeUser method.

**Comment by crystalztl** [comment]
https://github.com/braze-inc/braze-flutter-sdk/pull/15 Just found it is already PR-ed. Thanks!

**Comment by hokstuff** [comment]
Hi @crystalztl,

Thanks for filing this issue. As you noted above, there is the initial PR adding SDK auth support, and there is also a second PR here which adds error handling: https://github.com/braze-inc/braze-flutter-sdk/pull/20. I will close out this issue and you can reference those PRs until we add support directly in the main branch.
