### ISSUE TITLE
braze plugin no have function register ios apns token just only register android push token to setup at flutter code only

### ISSUE THREAD

**Issue by anggadwi16** [braze-inc/braze-flutter-sdk#23]
braze plugin no have function register ios apns token just only register android push token to setup at flutter code only. i think maybe can integrate with firebase token,

**Comment by wrbl606** [comment]
@Bucimis Though your solution may work isn't it something to be implemented on the Dart side? Isn't what this plugin is for?

**Comment by Bucimis** [comment]
@wrbl606 it's definitely a limitation, we're planning to address that going forward with full push support. The timeline is still not set though
