### ISSUE TITLE
Braze in Flutter Environment Production Not Working

### ISSUE THREAD

**Issue by rahmadiantio** [braze-inc/braze-flutter-sdk#25]
Currently, I have 2 environments in braze i.e. dev and prod which have different keys. Then in my flutter project I put the keys for dev in debug/res/values and for prod in prod/res/values. Once running, for a dev environment, you can track logged in users. But after changing to prod, user doesn't go to track. After checking the user to the track on the dev.

can in 1 project there are 2 key braze?

**Comment by Bucimis** [comment]
@rahmadiantio I would enable verbose logs and take a look at the request and response logs (https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#android-verbose-logging). That should give you a hint as to what's going wrong.

And yep, you can have two different API keys for braze depending on the build. They would be defined in your braze.xml, see https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration#multiple-api-keys

Closing as this isn't related to a bug in the Flutter SDK
