### ISSUE TITLE
[Bug]: Content cards ordering on Android

### ISSUE THREAD

**Issue by furkan-vatandas** [braze-inc/braze-flutter-sdk#31]
Hi, I'm getting content cards with subscribeToContentCards(or setBrazeContentCardsCallback) method on Android, but the ordering is different in every android user, there is no problem on the iOS side.

**Comment by hokstuff** [comment]
Hi @furkan-vatandas,

We have identified a slight difference between our sorting algorithms in the native iOS / Android SDKs and will update to make them consistent. To make sure it is the same root cause - do the two orderings differ greatly between the platforms, and are they updated based on interactions with the cards (e.g. clicks, impressions)?

**Comment by furkan-vatandas** [comment]
The cards are updated when I publish a new campaign, but ordering is still different in every android user and also "PIN TO TOP" feature is not working on Android.

**Comment by hokstuff** [comment]
Hi @furkan-vatandas,

We have released [Flutter SDK 3.1.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/3.1.0) which addresses the issue described above. Let us know if you are still experiencing issues - thanks!

**Comment by hokstuff** [comment]
Hi @furkan-vatandas,

Can you contact support@braze.com with the full list of Content Cards for both iOS and Android (via logs or any other way) to help compare and contrast the differences for each (if there are multiple users affected, it will be helpful to attach multiple instances)? Also please attach the link to this Github public issue so it's easy for them to associate with this issue.

Additionally, in the email, can you include whether or not you are using the default Content Card UI, or if you are doing any custom logic prior to displaying the cards?

Thanks!
