### ISSUE TITLE
[Feature] Can braze support In App Message Clicked Listener ?

### ISSUE THREAD

**Issue by zkjxx1548** [braze-inc/braze-flutter-sdk#33]
Background
Flutter: 2.10.5
braze_plugin: ^2.6.1

We want to use deep link in the braze In App Message buttons. And Parse the deep link when users click the In App Message button.

We used the `subscribeToInAppMessages` to handle the case when user receives an In App Message in flutter.
But there doesn't seem to be a way to listen to the click event.

Any suggestions?

**Comment by hokstuff** [comment]
Hi @zkjxx1548,

To log that an in-app message button is clicked in the Flutter layer, you can use [logInAppMessageButtonClicked ](https://github.com/braze-inc/braze-flutter-sdk/blob/5276be6c1ce7ec53219e04b4eede0f71ebed1e4f/lib/braze_plugin.dart#L168).

If you wish to add support for deeplinking, you will need to integrate deep links in the [native iOS and Android layers](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/push_notifications) of your application.

**Comment by zkjxx1548** [comment]
We found:
1. If we integrate In App Message in [Android](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/integration/#in-app-messaging-integration)
2. And use [Custom manager listener](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/custom_listeners/#:~:text=view%20hierarchy%20interaction-,Custom%20manager%20listener,-The%20BrazeInAppMessageManager%20automatically) to handle the case when click the In App Message button.

result: `subscribeToInAppMessages` in Flutter layer can not work.


Can **flutter-braze** dependency itself support In App Message Clicked listener ？

**Comment by hokstuff** [comment]
Hi @zkjxx1548,

Are you running into this issue on both iOS and Android?

On Android, when creating a custom in-app message manager listener, it overwrites any existing default one. Can you try adding a call to `BrazePlugin.processInAppMessage(inAppMessage)` inside your `beforeInAppMessageDisplayed` method like [in our sample here](https://github.com/braze-inc/braze-flutter-sdk/blob/5276be6c1ce7ec53219e04b4eede0f71ebed1e4f/android/src/main/kotlin/com/braze/brazeplugin/IntegrationInitializer.kt#L40)? This should pass the in-app message from the Android native layer to the Flutter layer to be processed.

**Comment by zkjxx1548** [comment]
Only running into android. 
Thanks for reply. I will try it.
