### ISSUE TITLE
[Bug]: Issue with Content Cards custom implementation

### ISSUE THREAD

**Issue by leofeng99** [braze-inc/braze-flutter-sdk#36]
When trying to custom implement Content Cards using `subscribeToContentCards`, the callback for content cards is not triggered when the content card list is empty inside the Braze SDK. A guard condition is found [here](https://github.com/braze-inc/braze-flutter-sdk/blob/master/lib/braze_plugin.dart#L535) that prevented the callback to be triggered.

In the case of there is only 1 content card left in the Braze SDK, when that card is either dismissed or expired, the card is removed from the Braze SDK content card list, but my application doesn't get notified via the subscribe callback due to the empty card list check. Therefore there is no way for my application to update custom content card UI to reflect the state change of the content card list (from 1 content card in the list -> empty content card list).

Is it possible to remove the condition linked above?

**Comment by hokstuff** [comment]
Hi @leofeng99,

Thanks for bringing up this issue! This guard statement was introduced in version 2.2.0, but your description above sounds like a valid use case. We will remove this check in our next release and respond back here when it is ready.

**Comment by leofeng99** [comment]
@hokstuff Awsome! Thanks!

**Comment by hokstuff** [comment]
Hi @leofeng99,

We just released the [Braze Flutter SDK version 3.0.1](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/3.0.1) which addresses this issue.

Thanks!
