### ISSUE TITLE
How to register device token on iOS for notification on version 3.0.0?

### ISSUE THREAD

**Issue by tamirrab** [braze-inc/braze-flutter-sdk#37]
How to register device token on iOS for notification on version 3.0.0?
Appboy_iOS_SDK is no longer available

**Comment by hokstuff** [comment]
Hi @tamirrab,

[Here are the developer docs](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b1-standard-push-notifications#Implement-the-push-notification-handlers) to implement registering an iOS device token using the updated Braze Swift SDK. Let me know if this answers your questions!

**Comment by tamirrab** [comment]
Thanks, it works :)
