### ISSUE TITLE
InAppMessages are "swallowed" given the suggested setup

### ISSUE THREAD

**Issue by JordyLangen** [braze-inc/braze-flutter-sdk#4]
When looking at this method:
https://github.com/braze-inc/braze-flutter-sdk/blob/master/android/src/main/kotlin/com/braze/brazeplugin/BrazePlugin.kt#L85

It seems that InAppMessages are completely discarded when the app is started in the background without an UI, which is a situation we are facing.

The README suggests the following:

> Your beforeInAppMessageDisplayed method implementation should return InAppMessageOperation.DISCARD. For an example, see MainActivity.kt in our example app.

So you get something like this:

```kotlin
    override fun beforeInAppMessageDisplayed(inAppMessage: IInAppMessage): InAppMessageOperation {
        Handler(Looper.getMainLooper()).post {
            BrazePlugin.processInAppMessage(inAppMessage)
        }

        return InAppMessageOperation.DISCARD
    }
```

I'm wondering if a setup like the following would be better:

```kotlin
    override fun beforeInAppMessageDisplayed(inAppMessage: IInAppMessage): InAppMessageOperation {
        if (!BrazePlugin.canProcessInAppMessages()) {
            return InAppMessageOperation.DISPLAY_LATER
        }

        Handler(Looper.getMainLooper()).post {
            BrazePlugin.processInAppMessage(inAppMessage)
        }

        return InAppMessageOperation.DISCARD
    }
```

This would mean that the braze plugin can provide this `canProcessInAppMessages` method.

Is this a solution that would work for the issue I described?

**Comment by Bucimis** [comment]
@JordyLangen I think you can try a few things:

1. Store the IAM in memory and call `BrazePlugin.processInAppMessage(inAppMessage)` when the app is ready.
2. Avoid triggering the IAM until the app is ready. This might involve moving from a session start to a custom event triggered IAM.

What is your use case for starting the app in the background without a UI?

**Comment by JordyLangen** [comment]
@Bucimis thanks for your reply.

We run the app in "headless" mode when we are handling events coming in for our geofencing & android widget functionalitites.

1. If we do this, in memory is not enough. Making this quite a complicated solution on our side.
2. That would indeed be the preferred solution, but human errors are not someting that can be avoided at all times 😉 

Would the `DISPLAY_LATER` mechanic work for our needs?

**Comment by Bucimis** [comment]
@JordyLangen `DISPLAY_LATER` would allow you to tell the SDK to store the IAM until a later time. However, note that the IAM instance would be stored in memory by the SDK, which may be problematic given your answer to 1.

**Comment by JordyLangen** [comment]
@Bucimis are there any intentions from your side investigating and fixing this issue?

**Comment by Bucimis** [comment]
@JordyLangen 

1. Would it work for your use case if `processInAppMessage` returned a boolean indicating whether the in-app message had been passed into the Flutter layer?
2. Could you provide verbose logs of the "completely discarded" case? I'm curious where in the display flow the IAM processing stops.

**Comment by JordyLangen** [comment]
@Bucimis 

1. That would only solve half of our problem, as then there is no reliable way to re-trigger the in-app messages.
2. I'll get back to you

**Comment by JordyLangen** [comment]
@Bucimis our testers where not possible to capture the logs for the given scenario.

**Comment by Bucimis** [comment]
@JordyLangen no worries! For a hypothetical `canProcessInAppMessages` method, what would you expect it to check? Would it basically check that a plugin activity exists, e.g.:

```
// rough pseudocode for canProcessInAppMessages
if (activePlugins.isEmpty()) {
  return false
}
for (plugin in activePlugins) {
  if (plugin.activity != null) {
    return true
  }
}
return false
```

**Comment by JordyLangen** [comment]
@Bucimis that would be great to check if we can actually show the message!

However, I think that still leaves us with the more difficult problem, which is what to do when `canProcessInAppMessages` returns `false`, as `DISPLAY_LATER` only does in-memory.

**Comment by Bucimis** [comment]
@JordyLangen Have you measured that the in-memory size of the IAM object is a problem? On Android, the code that actually downloads images and assets and adds heavyweight objects like Bitmaps to the IAM runs only after `DISPLAY_NOW` is returned. (See https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/utils/BackgroundInAppMessagePreparer.java and https://github.com/Appboy/appboy-android-sdk/blob/5248b0f6c6a221bee38b3f441cc19d4c11876ddb/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/BrazeInAppMessageManager.java#L302)

Up until that point, the IAM should be a relatively lightweight object consisting of a few strings/fields. The exception would be if you have IAMs with very long HTML messages or lots of key value pair extra data.

**Comment by JordyLangen** [comment]
@Bucimis the size of the messages is not the problem. In our case when the messages are lost, that specific flutter instance is always running in a headless mode. You explained to me that when using `DISPLAY_LATER` means the messages are preserved in memory, hence the next time the user starts the app the messages will be lost.

**Comment by hokstuff** [comment]
Hi @JordyLangen,

Just checking in about this original issue. It sounds like we settled on saying that this would be a product request, so the best way for this to get prioritized is by contacting your CSM and submitting a request that way.

Let us know if any of the workarounds provided above are sufficient! I will close out this issue, but feel free to reopen if you believe this is done in error.

Thank you!

**Comment by JordyLangen** [comment]
I've created a product request, but I'm not sure what the status is. The current workaround is to have our own custom "start session" event, which should be used as a trigger.
