### ISSUE TITLE
Upgrade to iOS swift-sdk 5.9.0

### ISSUE THREAD

**Issue by danielocampo2** [braze-inc/braze-flutter-sdk#40]
Currently this plugin is using braze-swift-sdk-5.6.4, which is from November 2022. After that, relevant fixes has been made, particularly the following in 5.9.0, that is affecting us directly:
```Fixes a behavior where the current user messaging data would not be directly available after initializing the SDK or calling changeUser(userId:).```

Do we have an ETA on when the next version will be released?

Thanks.

**Comment by hokstuff** [comment]
Hi @danielocampo2,

Thank you for raising signal around this! We don't currently have an ETA, but we will update to the latest Swift SDK version in the next release. Stay tuned on this thread for updates!

**Comment by danielocampo2** [comment]
Hi @hokstuff , thanks for the quick response!

Please let me know if this may be some error on our side, but currently the sdk seems to not be working properly so we cannot update until next release. Initialization is all correct, but then User Data is not properly linked when calling `changeUser`.
So when I open the app, instead of associating the install / usage with my user, it just creates a new random user with almost no data.

**Comment by hokstuff** [comment]
Hi @danielocampo2,

Updating this thread - we released version [3.1.0 of the Flutter SDK ](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/3.1.0)which contains the changes you were looking for above. Thanks!
