### ISSUE TITLE
[Feature]: Add push notification code into sample app

### ISSUE THREAD

**Issue by ghost** [braze-inc/braze-flutter-sdk#42]
Hi, the sample codes on Github and the document codes on the website are different, which one should we refer to?

Github : [AppDelegate.swift](https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.swift)
Document: [AppDelegate.swift](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/flutter_sdk_integration/#step-2-complete-native-setup)

**Comment by mahmoud-habashy** [comment]
i tried the sample code and it didn't work :(
app doesn't build with documentation codes.

**Comment by hokstuff** [comment]
Hi @furkan-vatandas,

Thanks for raising this! We have an internal task to update the [Flutter documentation on our Braze website](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/flutter_sdk_integration/#prerequisites) and will change that soon. For now, please reference the [Runner sample app code in Github](https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.swift) for an example integration to follow.

@mahmoud-habashy Have you added a content cards subscription like done [in the sample app](https://github.com/braze-inc/braze-flutter-sdk/blob/b054a756cb25f2661cec56c478a32f1e35f21f51/example/ios/Runner/AppDelegate.swift#L44)? This will pass any received Content card data models from the iOS host app -> iOS braze_plugin -> Dart braze_plugin.

**Comment by furkan-vatandas** [comment]
Thanks, I will check that. So, how do we initialize notification definitions?

**Comment by hokstuff** [comment]
Push notifications will need to be integrated in the native layer. You can reference this for [iOS push integration docs](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/b1-standard-push-notifications) and here for more general links to our migration guides for the [iOS Swift migration](https://github.com/braze-inc/braze-swift-sdk/).

**Comment by furkan-vatandas** [comment]
Can we add the implementation of the notification system in the native layer to the flutter sample project?

**Comment by hokstuff** [comment]
We are currently tracking this request internally and will note on this thread with any updates. Thanks!

**Comment by smn-snkl** [comment]
Same here. Tried to follow native integration part but not receiving any push notifications at this point ... Don't know what's happening

**Comment by spaluchiewicz** [comment]
The issue can be related to different way of Braze initialisation:
- this is for iOS `let braze = Braze(configuration: configuration)`
- this is (**required**) for Flutter `let braze = BrazePlugin.initBraze(configuration)` - this way correctly set reference to the native Braze which is required to handle communication to it. 

PushNotifications documentation for Flutter redirects to iOS documentation and here issue can be introduced.

**Comment by hokstuff** [comment]
Hi all,

We just released [Flutter version 7.0.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/7.0.0) which updates the sample app to integrate push notifications (iOS and Android) as well as support for deep links, universal links (iOS), and app links (Android). For the iOS push integration, it takes advantage of the Swift SDK's Push Automation feature (see sample code [in this file](https://github.com/braze-inc/flutter-sdk/blob/develop/braze_plugin/example/ios/Runner/AppDelegate.swift)), which allows the majority of the iOS push integration to be automated via setting a configuration.

Let us know if you have any further issues - thanks!
