### ISSUE TITLE
Unused static in example app?

### ISSUE THREAD

**Issue by RutgerVleuten** [braze-inc/braze-flutter-sdk#43]
In the AppDelegate of the example app static variable of type Braze (line 15) is never used.

**Comment by hokstuff** [comment]
Hi @RutgerVleuten,

The static variable `braze` in the sample app is intended to be an example to show how you can add customization in the iOS layer directly (e.g. by following [these docs to add a delegate](https://braze-inc.github.io/braze-swift-sdk/tutorials/braze/c1-inappmessageui)).

However, the `braze` instance is [held in BrazePlugin.swift](https://github.com/braze-inc/braze-flutter-sdk/blob/b054a756cb25f2661cec56c478a32f1e35f21f51/ios/Classes/BrazePlugin.swift#L557) and the [public APIs](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze) are already accessible via the `braze_plugin.dart`. If you do not want to do any customization in the iOS layer and wish to remove the static variable from your AppDelegate, that is up to you.

Thanks!

**Comment by RutgerVleuten** [comment]
Maybe I needed to add that the confusing part for me was that the same name was used for the let constant on line 34.

**Comment by hokstuff** [comment]
Ah, I see what you are referencing. The `static` braze instance isn't used or even set via 
```
AppDelegate.braze = braze
```
and there is no example using `BrazeInAppMessageUIDelegate`, so it is confusing. I'll remove it from the sample app to avoid further confusion - thanks for pointing this out!

**Comment by RutgerVleuten** [comment]
@hokstuff, ticket has closed status while it's not implemented yet.
