### ISSUE TITLE
'Braze in app message callback not present' message keeps spawning after subscribing

### ISSUE THREAD

**Issue by RutgerVleuten** [braze-inc/braze-flutter-sdk#44]
When moving from the deprecated setBrazeContentCardsCallback towards subscribeToContentCards we keep getting logging about "Braze content card callback not present ...".

I would expect the Stream approach to replace the Callback the message being logged is confusing in this case.

**Comment by hokstuff** [comment]
Hi @RutgerVleuten,

In your setup that you are seeing this, is it accurate to say that you:
- Have `replayCallbacksConfigKey` set to `true` in your custom config
- Only are implementing via Stream (`subscribeToContentCards`) and not via callback (`setBrazeContentCardsCallback`)

If so, it sounds like the wording [from these logs for content cards](https://github.com/braze-inc/braze-flutter-sdk/blob/4d69ff6c2f0a085aa5e9fccf59eac807980fa2b4/lib/braze_plugin.dart#L540) (and the complementary ones on in-app messages) imply the use of callbacks, even though the functionality replays for both callbacks and streams as expected. We will update the logs to be more generic or remove them entirely if they aren't helpful.

Thanks!

**Comment by hokstuff** [comment]
Hi @RutgerVleuten,

We have released our [Flutter SDK version 4.0.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/4.0.0), which removes the deprecated `setCallback` functionality. This also removes any confusing logs that would get printed when using `replayCallbacksConfigKey` alongside subscriptions via streams.

Thanks!
