### ISSUE TITLE
Suport Android 8 InApp campaign

### ISSUE THREAD

**Issue by fernandeslucassilva** [braze-inc/braze-flutter-sdk#53]
I am using the latest version of this plugin, but the InApp and Modal campaign does not work on Android 8. The screen freezes, like a transparent InApp or Modal. Nothing is shown. Can you help me?

**Comment by bryanlogan** [comment]
I've tried recreating and the In-App Modal campaign is working for me on Android 8.  I'm assuming it's working on all the other version of Android.

Do you want to reach out through the support channel so we can get more information that doesn't need to be posted publicly?

**Comment by hokstuff** [comment]
I'm closing this thread due to inactivity, and since our team believes our SDK does support Android 8.

If you have further issues, contact our Support team at support@braze.com. Thanks!
