### ISSUE TITLE
Braze Regiested firebase Toke to APPBOYreceiver

### ISSUE THREAD

**Issue by maheshmaersk** [braze-inc/braze-flutter-sdk#6]
Hello Team,
I am unable to attach my Firebase Token to appboy receiver. Since i need to send individual notifications to users that cannot happen without deviceID so any steps how to register and get the deviceID

@Bucimis  any suggestions which can be provied

**Comment by radixdev** [comment]
Hi @maheshmaersk ,

Are you using automatic Firebase registration? I don't understand what you mean by attaching a Firebase token to our receiver. Have you followed https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/ ?

**Comment by maheshmaersk** [comment]
We have followed same thing. And right now the document which has been shared is for flutter right? I mean I see native android integration but the same would work for braze as well? 

Please do correct me if I am wrong

**Comment by hokstuff** [comment]
Hi @maheshmaersk,

To integrate push notifications for your Flutter app, you will need to integrate push into each native layer. For the Android side, you can follow the instructions in the link provided above. Let us know if you have further issues or you can also contact support@braze.com.

Thanks!

**Comment by MarcusNg** [comment]
Hi @hokstuff - Is there an example repo of an Android and Braze integration using [firebase_messaging](firebase_messaging)?

I was able to get Braze Android campaign push notifications to show up in my Android emulator's notification drawer by following the instructions linked above. However, none of the `firebase_messaging` callbacks (e.g. `FirebaseMessaging.onMessageOpenApp`) receive a new stream event when I open a notification.

What is the proper way to receive notification open stream events in Flutter applications when opening push notifications from Braze? I've set up a [BroadcastReceiver](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#custom-handling-for-push-receipts-opens-dismissals-and-key-value-pairs), but I'm not sure what the next steps are. Thanks!

**Comment by radixdev** [comment]
Hi @MarcusNg ,

Android push notifications are sent as data messages through the manifest registered [BrazeFirebaseMessagingService](https://github.com/Appboy/appboy-android-sdk/blob/9e710e1d49cad78933e124bb67cbe6d1df228dcb/android-sdk-ui/src/main/java/com/braze/push/BrazeFirebaseMessagingService.java) and thus wouldn't go through whatever FCM service is registered in that linked `firebase_messaging` flutter package. 

We will be auditing our sample app and flutter documentation to make sure the android push setup is as clear and bespoke to Flutter as possible. We'll update this issue once that's complete.

**Comment by hokstuff** [comment]
Hi @MarcusNg,

Are you still experiencing this issue? We have also released Flutter SDK [version 2.2.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/2.2.0) which simplifies the Firebase token registration process. Let us know if this helps!

Best,
Daniel

**Comment by hokstuff** [comment]
That sounds good, glad to hear you were able to figure it out on your end. I'm going to close out this issue - thanks!
