### ISSUE TITLE
v7.0.0 isn't compatible with Flutter Android version

### ISSUE THREAD

**Issue by rayliverified** [braze-inc/braze-flutter-sdk#60]
Flutter currently supports SDK target 33, not 34.
The latest Braze plugin requires targetSDK version 34.

> ERROR:D8: com.android.tools.r8.kotlin.H
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:mergeExtDexQaDebug'.
> > Could not resolve all files for configuration ':app:qaDebugRuntimeClasspath'.
>    > Failed to transform kotlin-stdlib-1.9.10.jar (org.jetbrains.kotlin:kotlin-stdlib:1.9.10) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
>       > Execution failed for DexingWithClasspathTransform: C:\Users\searc\.gradle\caches\transforms-3\af5f39658d01b01dc753e42a71ae4269\transformed\jetified-kotlin-stdlib-1.9.10.jar.
>          > Error while dexing.

**Comment by rayliverified** [comment]
Here are the compatible gradle versions.

`build.gradle`
![snap_screen_20231027112432](https://github.com/braze-inc/braze-flutter-sdk/assets/19896174/deb58ff6-a201-497a-8f41-425e59ec47ea)

`gradle-wrapper.properties`
![snap_screen_20231027112459](https://github.com/braze-inc/braze-flutter-sdk/assets/19896174/50672967-653f-44f4-9e05-b6e36cd4d298)

Please keep in mind that the latest versions of of gradle are not compatible with Flutter until Flutter officially supports them. Always use the version of gradle that Flutter officially supports.

**Comment by hokstuff** [comment]
Hi @rayliverified,

Can you link to the Flutter documentation that describes that Flutter does not support Android API 34? According to the official [Flutter supported deployment platforms article](https://docs.flutter.dev/reference/supported-platforms#deploying-flutter) and the [_What’s new in Flutter 3.13 blog post_](https://medium.com/flutter/whats-new-in-flutter-3-13-479d9b11df4d#a7be:~:text=With%20this%20release%2C%20Flutter%20now%20supports%20targeting%20Android%2014/%20API%2034), Android API 34 is supported by the most recent minor version of Flutter released in August. Would you be able to update to that version and see if you are still experiencing errors? We can update any relevant documentation on our end to reflect these changes.

Let me know if you have any concerns or comments. Thank you!

**Comment by rayliverified** [comment]
Flutter supports SDK v34 but not as the targetSDK version.

`flutter.compileSdkVersion` = 33

**Comment by hokstuff** [comment]
Thanks for raising this! We've filed a ticket internally to make this change and will keep this thread updated when we have released a change.

**Comment by rayliverified** [comment]
Thank you!
This is an area where Flutter can specify the constraints more clearly. 

The way I keep up to date on what versions Flutter support is running `flutter create .`, creating a new project, and seeing what the generated files use.

**Comment by hokstuff** [comment]
Hi @rayliverified,

We have released [Flutter SDK 8.0.0 ](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/8.0.0)which includes a change for this issue.

Thanks!
