### ISSUE TITLE
How can I add custom sound on braze notification in flutter

### ISSUE THREAD

**Issue by prashantmwork** [braze-inc/braze-flutter-sdk#62]
I explored the documentation but I didn't get much more idea from that, so could you please help me to add a custom sound for notification?

**Comment by hokstuff** [comment]
Hi @prashantmwork,

You can reference [these docs](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/push_notifications/customization/custom_sounds) about creating custom sounds for iOS push notifications. For Android, you can reference [these docs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/customization/advanced_settings/#sounds). Also note that both of these must be done in the native layer directly.

If you have any further questions, feel free to contact support@braze.com. Thanks!
