### ISSUE TITLE
Missing information on braze content cards when resending campaign

### ISSUE THREAD

**Issue by sam-nixplay** [braze-inc/braze-flutter-sdk#68]
Whenever we do an edit on a campaign and resend it to the users, the content card information received from the Braze SDK when calling `braze.getCachedContentCards()`, it returns the right amount of content cards, however the edited ones are missing all of their information like (see attachted screenshot from visual studio code debugging)

<img width="822" alt="Screenshot 2024-03-27 at 16 06 15" src="https://github.com/braze-inc/braze-flutter-sdk/assets/138649649/3041d3b4-bfab-4e72-9927-f3277285f23e">

**Comment by hokstuff** [comment]
Hi @sam-nixplay,

Can you send an email with more information to support@braze.com so we can understand the context around your issue? Please include responses to:
1. What was in your campaign originally, and what did you edit it to?
2. `getCachedContentCards()` grabs the cached content cards, so it may be out of date. Have you tried using [`subscribeToContentCards()`](https://github.com/braze-inc/braze-flutter-sdk/blob/master/lib/braze_plugin.dart#L79) and then calling `requestContentCardsRefresh()` to ensure that you are getting the up-to-date list of cards?
3. Attach your campaign(s) to the email so the Support team is able to debug further. Also, include a link to this Github public issue.

Thanks!

**Comment by 0aps** [comment]
I have seen this problem as well from time to time. It's not a matter of using subscribeToContentCards. @hokstuff

**Comment by hokstuff** [comment]
Hi @sam-nixplay @0aps,

Based on the screenshot above, it looks like the Content Card is a `control` card, which is expected not to have content in the payload. In your campaign, there is an option to turn off the A/B Testing option that sends "Control Group" content cards if you wish to always receive the full content in the payloads. This would also explain why the problem only occurs `from time to time`.

Specifically, if you go to the third tab `Target` in your campaign, you can turn off the "Control Group" option
![image](https://github.com/braze-inc/braze-flutter-sdk/assets/4797040/c5dabb51-af4d-451b-b3d3-bcba2d1726d0)

---

I will close out this issue based on ^. After these changes, if you continue to run into issues, please contact our Support team by emailing support@braze.com. This will allow for quicker back-and-forth and make it easier to send details specific to your integration.

Thanks!
