### ISSUE TITLE
Support for setting `.trackingPropertyAllowList` from Dart layer

### ISSUE THREAD

**Issue by wrbl606** [braze-inc/braze-flutter-sdk#69]
As [described in your documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/privacy_manifest/#step-2-declare-your-tracking-data), the new iOS'es Privacy-Manifest-related require a statement of the property and event names delivered to Braze's instance.

Hence the tracking is happening on the Dart side, it would make a lot of sense to declare those tracking details there too. Do you have any plans or a timeline for supporting this configuration feature from the Dart side?

**Comment by jerielng** [comment]
Hey @wrbl606, yep! We're actually actively working on this feature at the moment and will let you know when it's been released. Thanks!

**Comment by hokstuff** [comment]
Hi @wrbl606,

We have released support for setting the iOS tracking properties in [Flutter version 9.0.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/9.0.0). Let us know if you run into any issues - thanks!
