### ISSUE TITLE
 Undefined symbols: linker command failed with exit code 1 

### ISSUE THREAD

**Issue by FlashLampo** [braze-inc/braze-flutter-sdk#72]
Hi guys, I installed the braze 10.0.0 package for Flutter, but when I try to build, xcode returns the following error:

> ld: warning: Could not find or use auto-linked framework 'BrazeArchitecture': framework 'BrazeArchitecture' not found
ld: warning: Could not find or use auto-linked framework 'BrazeCasePaths': framework 'BrazeCasePaths' not found
ld: warning: Could not find or use auto-linked framework 'BrazeComposableArchitecture': framework 'BrazeComposableArchitecture' not found
ld: warning: Could not find or use auto-linked framework 'CMinizipNg': framework 'CMinizipNg' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'NanoCombine': framework 'NanoCombine' not found
ld: warning: Could not find or use auto-linked framework 'NanoCombineExt': framework 'NanoCombineExt' not found
ld: warning: Could not find or use auto-linked framework '_BrazeAssetsClient': framework '_BrazeAssetsClient' not found
ld: warning: Could not find or use auto-linked framework '_BrazeUnzipClient': framework '_BrazeUnzipClient' not found
ld: warning: Could not find or use auto-linked framework '_BrazeUtils': framework '_BrazeUtils' not found
ld: Undefined symbols:
  static ActivityKit.Activity.pushToStartTokenUpdates.getter : ActivityKit.Activity<A>.PushTokenUpdates, referenced from:
      (1) suspend resume partial function for closure #2 @Sendable () async -> () in BrazeKit.Braze.LiveActivities.registerPushToStart<A where A: ActivityKit.ActivityAttributes, A: BrazeKit.BrazeLiveActivityAttributes>(forType: ActivityKit.Activity<A>.Type, name: Swift.String) -> Swift.Task<(), Swift.Never> in BrazeKit[arm64][2](BrazeKit-arm64-master.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Xcode version 15.0 (15A240d)
Flutter version 3.10.5
Dart version 3.0.5

**Comment by lowip** [comment]
Hi @FlashLampo,

Thank you for opening this issue.
Since `9.0.0`, our Flutter plugin requires Xcode 15.2+. This is missing from the `9.0.0` changelog entry, we'll make sure to update it.

Best,

**Comment by 0aps** [comment]
@lowip I'm on Xcode 15.3 and getting the same problem stated above:

<img width="573" alt="image" src="https://github.com/braze-inc/braze-flutter-sdk/assets/1641716/922911de-1c04-4dbf-af8b-cfe7b3b2743a">

Any clue what this might be?
