### ISSUE TITLE
No Push notification on Android

### ISSUE THREAD

**Issue by sumitssn** [braze-inc/braze-flutter-sdk#73]
Getting below log on android but not receiving any push notification

I/Braze v30.3.0 .g1( 7412): Event was published, but no subscribers were found. Saving event for later publishing to a matching subscriber. Event class: class com.braze.events.BrazePushEvent this bo.app.g1@89e7d7e

Not able to get call back in  pushEventHandler: (data) {}, nor getting any events from _braze.subscribeToPushNotificationEvents((events)

**Comment by hokstuff** [comment]
Hi @sumitssn,

Can you contact support@braze.com with more information so we can debug your issue:
1. Steps to repro
2. Push integration code
3. Verbose logs

Thanks!

**Comment by vanessaland** [comment]
Hi @sumitssn,

I'll be closing this issue now due to inactivity. If you need any additional support, please reach out to [support@braze.com](mailto:support@braze.com).

Thank you!
