### ISSUE TITLE
Unable to perform content cards operation, the content cards feature is disabled - in iOS

### ISSUE THREAD

**Issue by lironzemingo** [braze-inc/braze-flutter-sdk#75]
Hi,
Imlemented Braze content cards, and it works great in Android, but not in iOS. any ides what could be causing this? what should I be looking for?:

this is my AppDelegate code:
```

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    static var braze: Braze? = nil
    var contentCardsSubscription: Braze.Cancellable?
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
      
      let infoDictionary = Bundle.main.infoDictionary ?? ["BrazeApiKey": ""]
                let brazeKey = infoDictionary["BrazeApiKey"] as? String ?? ""
     // print("brazeKey: \(brazeKey)")
    let configuration = Braze.Configuration(apiKey: brazeKey, endpoint:"sdk.bbbbbb.eu")
      configuration.logger.level = .info
      let braze = BrazePlugin.initBraze(configuration)
      AppDelegate.braze = braze
      contentCardsSubscription = braze.contentCards.subscribeToUpdates { contentCards in
        print("=> [Content Card Subscription] Received cards:", contentCards)
        BrazePlugin.processContentCards(contentCards)
      }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```
and these are some Braze logs I see:

```
[braze] Initializing Braze SDK 7.7.0 with configuration:
- api
  - key: 
  - endpoint: sdk.fra-02.braze.eu
  - requestPolicy: automatic
  - flushInterval: 10.0
  - sdkAuthentication: false
  - sdkMetadata: ["flutter", "manual"]
  - trackingPropertyAllowList: []
- push
  - appGroup: nil
  - automation (disabled)
- location (disabled)
- logger
  - level: .info
  - signposts: false
  - print: default
- sessionTimeout: 10.0
- triggerMinimumTimeInterval: 30.0
- useUUIDAsDeviceId: true
- forwardUniversalLinks: false
- optInWhenPushAuthorized: true
- tvOSPersistedSizeLimit: 131072
[braze] The value is not supported.
- value: ""
- type: Swift.String
- location: BrazeKit/ConfigurationExt.swift:8
- function: errors
- parameter: api.key
=> [Content Card Subscription] Received cards: []

[braze] Ended user session (id: XXXXX, duration: 839s).
[braze] Started user session (id: YYYYY).

[braze] Platform api error.
- reason: invalid_api_key
[braze] No matching trigger for event.
- event: open

[braze] Platform api error.
- reason: invalid_api_key
[braze] Platform api error.
- reason: invalid_api_key
[braze] Platform api error.
- reason: invalid_api_key
[braze] Platform api error.
- reason: invalid_api_key

[braze] Current user is already identified as "aaaaaa".
```
and this when trying to call  `_brazePlugin.subscribeToContentCards()...`

`[braze] Unable to perform content cards operation, the content cards feature is disabled.
`

**Comment by vanessaland** [comment]
Hi @lironzemingo,

Thanks for reaching out! Here are some things you can try to help resolve your issue:
- Check to see if you are importing the correct modules in your AppDelegate, such as `UIKit` and `BrazeUI`. See the [Sample App](https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/ios/Runner/AppDelegate.swift#L1-L7) for an example.
- Check to see if you are correctly listening to the stream in the Dart layer. See the [Developer Doc](https://www.braze.com/docs/developer_guide/platform_integration_guides/flutter/content_cards/?tab=ios#step-1-listen-for-content-card-data-in-the-dart-layer) and [Sample App](https://github.com/braze-inc/braze-flutter-sdk/blob/master/example/lib/main.dart#L517-L531) for reference.

If you continue to run into issues, please contact our Support team by emailing [support@braze.com](mailto:support@braze.com). They will be able to help with your specific integration. In your email, please include:
- AppDelegate
- Dart layer
- Verbose Logs

Thanks!

**Comment by vanessaland** [comment]
Hi @lironzemingo ,

I'll be closing this issue now due to inactivity. If you need any additional support, please reach out to [support@braze.com](mailto:support@braze.com). 

Thank you!
