### ISSUE TITLE
 Braze Push Notifications in Release Mode

### ISSUE THREAD

**Issue by babakoto** [braze-inc/braze-flutter-sdk#76]
Hello 
We have successfully integrated Braze push notifications in our mobile application, and everything works perfectly in debug mode on both iOS and Android. However, we encounter a problem when running the app in release mode: push notifications are no longer received.

Could you please assist us in resolving this issue?

Framework : Flutter 3.22.0
dependencies:
  braze_plugin: ^10.1.0

Thank you for your support.

**Comment by hokstuff** [comment]
Hi @babakoto,

To help assist with this issue, can you raise it in our Support channel in an email to support@braze.com? It will be much more efficient given there will likely be back-and-forth as we find out more around your specific setup.

I suspect you may be attempting to send a push notification to a release build through the iOS APNs Development Gateway, which will silently fail. If that is the case, you will need to set up a separate App in your Braze Dashboard with a new API key to send to the iOS APNs Production Gateway, which the Support team will help with. Also, in the conversation with Support, we will ask for verbose logging, your current setup on the Braze dashboard, and whether or not this occurs on Android.

Thanks!
