### ISSUE TITLE
Early returning because the Braze instance isn't fully initialized

### ISSUE THREAD

**Issue by EdwardHalapi** [braze-inc/braze-flutter-sdk#79]
I have tried to integrate Braze sdk in a flutter app, I have followed the documentation regarding the integration of the sdk in flutter but I still encountered a problem. Error log:

"Early returning because the Braze instance isn't fully initialized. Always use Braze.getInstance(context) to get the latest Braze instance. Please report to Braze if the issue continues. Failed to log custom event"
"Early returning because the Braze instance isn't fully initialized. Always use Braze.getInstance(context) to get the latest Braze instance. Please report to Braze if the issue continues. Failed to set external id to: 6"
I am initializeing the braze plugin like this:

 braze = BrazePlugin();
using this instance I try to logCustomEvents and to use changeUser method. Braze.getInstance(context) does not exist in the flutter plugin.

Here is what I did to integrate the SDK:

created braze.xml file in the main/res/value folder

added the braze_plugin package to my pubspec.yaml

**Comment by hokstuff** [comment]
Hi @EdwardHalapi,

It sounds like you are facing integration issues with the Android side of your Flutter app. Can you contact support@braze.com with more information about your current integration setup, including verbose logs, integration code, and steps to repro? It will be easier for back-and-forth than a Github issue. I will also close out this issue in favor of a Support ticket with our team.

Thanks!
