### ISSUE TITLE
Content card logging documentation is incomplete

### ISSUE THREAD

**Issue by JordyLangen** [braze-inc/braze-flutter-sdk#8]
Looking at the inline docs, we have this:

https://github.com/braze-inc/braze-flutter-sdk/blob/487384e8eba9e81c1ac42a4475cd7ef6031f9c78/lib/braze_plugin.dart#L35-L36

and this

https://github.com/braze-inc/braze-flutter-sdk/blob/487384e8eba9e81c1ac42a4475cd7ef6031f9c78/lib/braze_plugin.dart#L43-L44

Whats the actual difference? Or is this wrongly documented?

**Comment by radixdev** [comment]
Hi @JordyLangen ,

This was an issue with our documentation and has been resolved. Thank you for filing this issue!

The `logContentCardImpression` method does indeed log a Content Card impression and not a click.

**Comment by hokstuff** [comment]
Hi @JordyLangen,

We just released Flutter SDK [version 2.2.0](https://github.com/braze-inc/braze-flutter-sdk/releases/tag/2.2.0) which fixes the documentation concern described here. Thanks!
