### ISSUE TITLE
BrazeSdkAuthenticationErrorCallback will trigger multiple times when calling changeUser with an expired token.

### ISSUE THREAD

**Issue by guixijing** [braze-inc/braze-flutter-sdk#80]
We are using the latest braze plugin 10.1.0 with SDK Authentication enabled.

But when call `changeUser()` with invalid token or expired token. The callback in setBrazeSdkAuthenticationErrorCallback(callbackFunction) will be triggered more than once nearly in the same time. 

Could you help to have a look?

**Comment by vanessaland** [comment]
Hi @guixijing ,

Can you please contact [support@braze.com](mailto:support@braze.com) with more information about your current integration setup, including:
- Verbose logs
- Integration code (code snippets of `changeUser`, `setBrazeSdkAuthenticationErrorCallback` implementations)
- Steps to reproduce the issue 

The Support Team will be able to help you with your specific implementation and the issues you are seeing. I will also close out this issue in favor of a Support ticket with our team.

Thanks!
