### ISSUE TITLE
"None of the selected users have matching push tokens for iOS Push"

### ISSUE THREAD

**Issue by douglashetherington** [braze-inc/braze-flutter-sdk#9]
os: iOS
braze_plugin: 2.1.0
flutter:2.5.1

Hi folks! :) 

I think I've followed the instructions in the readme for this plugin. However the braze UI won't send any pushes. It says "None of the selected users have matching push tokens for iOS Push". 

I have push notifications working in the app with firebase at the moment, so the overall app setup/signing is probably ok. I have the user permissions request working.

What I presume I'm missing is the sending of the device token to braze (unless it's done automagically under the hood) - I have the APNS token on the flutter side but there's no api to send it to. (There is one for Android though) 

What's the correct way to set this up?  Do I need to send this from the native code in the iOS runner?

**Comment by Bucimis** [comment]
Hi @douglashetherington,

Thanks for checking in! Yes, you will need to pass your device token to Braze through the `Appboy.registerDeviceToken()` in the native Braze iOS SDK.

https://github.com/Appboy/appboy-ios-sdk/blob/master/HelloSwift/HelloSwift/AppDelegate.swift#L44 provides an example. (You should also use this example to implement the delegate methods that are used for push handling. See https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/ for the complete instructions)

We will also be updating our Flutter samples to provide a same-repo example. We also have a longer term roadmap issue to remove any native iOS code from the push integration, but that won't be available for some time.

**Comment by hokstuff** [comment]
Hi @douglashetherington,

Are you still experiencing issues when registering your app for push notifications?

Thanks!

**Comment by douglashetherington** [comment]
Hi @hokstuff all fixed  - I did what @Bucimis said and it spang into life.
