### ISSUE TITLE
[Bug]: board error

### ISSUE THREAD

**Issue by M2dL1fe** [braze-inc/braze-flutter-sdk#95]
### Which Platforms?

iOS

### Which Flutter Version?

3.24.6

### Which Braze Flutter SDK version?

12.0

### Repro Rate

100%

### Steps To Reproduce

0

### Expected Behavior

0

### Actual Incorrect Behavior

0

### Additional Information

Braze seems to record my iPhone 11 under Android device.

The “last used” date is recorded for Android device but not for IOS device.

![image](https://github.com/user-attachments/assets/604eec10-5e6c-4fe4-8a0a-94ca43a82fd0)

**Comment by hokstuff** [comment]
Hi @M2dL1fe,

Please reach out to support@braze.com with more information so we can debug this further. The Support team will ask you for information such as Steps to repro, verbose logs of the repro, as well as other information like any other devices you may use.

Thanks!
